name: Rust-Release

on:
  workflow_dispatch:

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc


    runs-on: ${{ matrix.platform.os }}

    name: Release on multiple os

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
        GITHUB_TOKEN: ${{ github.token }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: cert-monitor
          target: ${{ matrix.platform.target }}-${{github.event.release.tag_name}}
          action-gh-release-parameters: |
            {
                "repository": "crisobal/cert-monitor"                
            }
      
